version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/conf/conf.d/:/etc/nginx/conf.d/
      - ./nginx/log/:/var/log/nginx/
      - ./public:/var/www/laravel/public
    depends_on:
      - nuxt
      - phpfpm
  nuxt:
    build:
      context: .
      dockerfile: ./dockerfile/nuxt.dockerfile
    volumes:
      - .:/app
  phpfpm:
    build:
      context: .
      dockerfile: ./dockerfile/phpfpm.dockerfile
    volumes:
      - .:/var/www/laravel
    environment:
      DB_HOST: mysql
      DB_DATABASE: mysql_db
      DB_USERNAME: username
      DB_PASSWORD: password
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mysql_db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      TZ: 'Azia/Tokyo'
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    command: --innodb-use-native-aio=0
